//! Generate `finupdate.h` from `src/ffi.rs` so the cc-panel C code doesn't
//! have to maintain the prototypes by hand. Runs every cargo build; cheap
//! enough that the convenience beats stamping it.
//!
//! Output: `$OUT_DIR/include/finupdate.h`. The cc-panel build picks the
//! header up via:
//!
//! ```sh
//! pkg-config --cflags-only-I libfinupdate
//! ```
//!
//! where the `libfinupdate.pc` file is generated by the panel's own meson
//! build (cc-panel/meson.build). For developers building both sides in
//! tree, the path is hard-coded to `../target/<profile>/include/finupdate.h`.

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");

    // Place the header alongside the cdylib output so the cc-panel build
    // can find both with a single `-L target/<profile>` / `-I target/<profile>/include`.
    let target_dir = env::var("OUT_DIR")
        .map(PathBuf::from)
        .and_then(|p| {
            // OUT_DIR is e.g. target/debug/build/finupdate-xxx/out — walk
            // back up to target/debug.
            p.ancestors()
                .nth(3)
                .map(|x| x.to_path_buf())
                .ok_or(env::VarError::NotPresent)
        })
        .unwrap_or_else(|_| PathBuf::from(&crate_dir).join("target/debug"));
    let include_dir = target_dir.join("include");
    std::fs::create_dir_all(&include_dir).expect("create include dir");
    let header_path = include_dir.join("finupdate.h");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        // Match the gnome-control-center style: lowercase functions,
        // PascalCase types. cbindgen does this by default for Rust →
        // C, leave the rest at defaults.
        include_guard: Some("FINUPDATE_H".to_string()),
        autogen_warning: Some(
            "/* Generated by cbindgen from src/ffi.rs. Do not edit. */".to_string(),
        ),
        documentation: true,
        // Prefix enum variants with the enum name so they don't collide
        // in C's flat global namespace. Three of our enums have an
        // `Unknown` variant — without this, the C side wouldn't compile.
        // Produces e.g. `FinupdateEventKind_Output` / `FinupdateModule_System`.
        enumeration: cbindgen::EnumConfig {
            prefix_with_name: true,
            ..Default::default()
        },
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&header_path);
            println!(
                "cargo:warning=Generated C header at {}",
                header_path.display()
            );
        }
        Err(e) => {
            // Don't fail the build — cbindgen errors block iteration on
            // the Rust side. Print a warning so the dev knows the header
            // isn't fresh.
            println!("cargo:warning=cbindgen failed (header not regenerated): {e}");
        }
    }

    println!("cargo:rerun-if-changed=src/ffi.rs");
}
